version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: alura-postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

  prometheus:
    image: prom/prometheus:latest
    container_name: alura-prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - postgres

  grafana:
    image: grafana/grafana:latest
    container_name: alura-grafana
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - prometheus

volumes:
  postgres_data: